apiVersion: v1
kind: Service
metadata:
  name: service-two-service
  labels:
    app: service-two
    mode: basic
    category: learning
spec:
  type: NodePort
  selector:
    app: service-two
    mode: basic
    category: learning
  ports:
    - port: 7000
      targetPort: 9002
      nodePort: 30902
      protocol: TCP